// F&O Stock List - NSE Futures & Options Stocks
// These are the most liquid stocks for swing trading

export const FO_STOCKS = [
  // NIFTY 50 Major Stocks
  'RELIANCE',
  'TCS',
  'HDFCBANK',
  'INFY',
  'ICICIBANK',
  'HINDUNILVR',
  'SBIN',
  'BHARTIARTL',
  'KOTAKBANK',
  'ITC',
  'LT',
  'AXISBANK',
  'BAJFINANCE',
  'ASIANPAINT',
  'MARUTI',
  'TITAN',
  'SUNPHARMA',
  'TMPV', // Tata Motors Passenger Vehicles (renamed Oct 2025)
  'ULTRACEMCO',
  'NTPC',
  'WIPRO',
  'POWERGRID',
  'NESTLEIND',
  'TECHM',
  'HCLTECH',
  'ONGC',
  'TATASTEEL',
  'JSWSTEEL',
  'ADANIENT',
  'ADANIPORTS',
  'BAJAJFINSV',
  'COALINDIA',
  'HINDALCO',
  'GRASIM',
  'DRREDDY',
  'CIPLA',
  'APOLLOHOSP',
  'BPCL',
  'DIVISLAB',
  'EICHERMOT',
  'HEROMOTOCO',
  'INDUSINDBK',
  'BRITANNIA',
  'SBILIFE',
  'HDFCLIFE',
  'M&M',
  'TATACONSUM',
  'BAJAJ-AUTO',
  'LTIM',
  'TRENT',

  // Bank Nifty Components
  'AUBANK',
  'BANDHANBNK',
  'FEDERALBNK',
  'IDFCFIRSTB',
  'PNB',

  // Additional F&O Stocks
  'DMART',
  'PIDILITIND',
  'BERGEPAINT',
  'HAVELLS',
  'VOLTAS',
  'GODREJCP',
  'MARICO',
  'DABUR',
  'COLPAL',
  'MUTHOOTFIN',
  'BAJAJHLDNG',
  'CHOLAFIN',
  'SHRIRAMFIN',
  'MOTHERSON',
  'TVSMOTOR',
  'MRF',
  'BOSCHLTD',
  'SIEMENS',
  'ABB',
  'CUMMINSIND',
  'TORNTPHARM',
  'LUPIN',
  'ALKEM',
  'IPCALAB',
  'PERSISTENT',
  'COFORGE',
  'MPHASIS',
  'LTTS',
  'ZOMATO',
  'PAYTM',
  'POLICYBZR',
  'NYKAA',
  'DLF',
  'GODREJPROP',
  'OBEROIRLTY',
  'IRCTC',
  'INDIGO',
  'TATAPOWER',
  'ADANIGREEN',
  'ADANIPOWER',
  'JINDALSTEL',
  'SAIL',
  'NMDC',
  'VEDL',
  'HAL',
  'BEL',
  'GAIL',
  'IOC',
  'PETRONET',
  'IGL',
  'MGL',
  'PIIND',
  'UPL',
  'SRF',
  'ATUL',
  'DEEPAKNTR',
  'INDUSTOWER',
  'IDEA',

  // Additional NIFTY 200 stocks
  'ACC',
  'AMBUJACEM',
  'AUROPHARMA',
  'BALKRISIND',
  'BATAINDIA',
  'BHEL',
  'BIOCON',
  'CANBK',
  'CONCOR',
  'CROMPTON',
  'CUB',
  'DIXON',
  'ESCORTS',
  'EXIDEIND',
  'GLENMARK',
  'GMRINFRA',
  'GNFC',
  'GRANULES',
  'GSPL',
  'HDFCAMC',
  'HINDPETRO',
  'ICICIPRULI',
  'ICICIGI',
  'IDFC',
  'INDHOTEL',
  'IRFC',
  'JKCEMENT',
  'JUBLFOOD',
  'LAURUSLABS',
  'LICHSGFIN',
  'LTF',
  'MANAPPURAM',
  'MCDOWELL-N',
  'MCX',
  'METROPOLIS',
  'NAM-INDIA',
  'NATIONALUM',
  'NAUKRI',
  'NAVINFLUOR',
  'NBCC',
  'NCC',
  'OFSS',
  'PAGEIND',
  'PEL',
  'PFC',
  'POLYCAB',
  'PVRINOX',
  'RAMCOCEM',
  'RECLTD',
  'SBICARD',
  'SHREECEM',
  'STARHEALTH',
  'SUNTV',
  'SUPREMEIND',
  'SYNGENE',
  'TATACHEM',
  'TATACOMM',
  'TATAELXSI',
  'TATAMTRDVR',
  'TORNTPOWER',
  'TTML',
  'UBL',
  'UNIONBANK',
  'UNITDSPR',
  'VBL',
  'WHIRLPOOL',
  'ZEEL',
  'ZYDUSLIFE',
];

// Yahoo Finance format - append .NS for NSE
export function getYahooSymbol(symbol: string): string {
  return `${symbol}.NS`;
}

// Get list of Yahoo symbols
export function getYahooSymbols(): string[] {
  return FO_STOCKS.map(getYahooSymbol);
}
